name: Tervehdys
version: '${version}'
main: me.Toivow.tervehdys.Tervehdys
api-version: '1.21'
author: Toivow
description: Tervehdys join/leave message
softdepend: [LuckPerms]
commands:
  tervehdys:
    description: Tervehdys reload
    usage: /<command> reload
    permission: tervehdys.reload
    permission-message: "<red>Ei oikeuksia käyttää tätä komentoa."
permissions:
  tervehdys.reload:
    description: Sallii /tervehdys reload -komennon käytön
    default: op